config/routes.rb
GlobalFriends::Application.routes.draw do
  devise_for :users

  resources :properties do
    resources :reviews
  end
  resources :users, only: [:index, :show, :update]

  resources :reviews

  resources :pictures, only: [:show, :destroy, :update]


  root to: 'properties#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :properties
  has_many :pictures
  has_many :reviews

  after_create :send_signup_confirmation



private
  def send_signup_confirmation
    UserMailer.signup_confirmation(self).deliver
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    authorize! :manage, User
  end

  def show
    @user = User.find(params[:id])
    authorize! :manage, User
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    flash[:notice] = "#{@user.username} has had his/her privileges adjusted."
    redirect_to user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:role)
  end
end

app/views/users/index.html.erb
<h3>Manage Users</h3>
<ul>
<% @users.each do |user| %>
  <li><%= link_to user.username, user_path(user) %></li>
<% end %>

app/views/users/show.html.erb
<h3><%= @user.username %></h3>
<p>Role: <%= @user.role %></p>
<p>Properties:</p>
<ul>
  <% if @user.properties.length == 0 %>
    <li><%= @user.username %> has not (yet) added any properties.</li>
  <% else %>
    <% @user.properties.each do |property| %>
      <li><%= link_to property.name, property_path(property) %></li>
    <% end %>
  <% end %>
</ul>
Reviews:
<ul>
  <% if @user.reviews.length == 0 %>
    <li><%= @user.username %> has not (yet) reviewed any properties.</li>
  <% else %>
    <% @user.reviews.each do |review| %>
      <li>
        <p><b><%= review.header %></b><br />
        <%= review.body %><br />
        Reviewed by: <%= review.user.username %><br />
        Reviewed on: <%= review.created_at.strftime("%m/%d/%Y") %>
      </li>
    <% end %>
  <% end %>
</ul>

<% if @user.role == 'admin' %>
  <%= form_for @user do |f|%>
    <%= f.hidden_field :role, value: 'member' %>
    <%= f.submit "Revoke Admin Privileges", class: 'btn btn-danger btn-sm', confirm: "Is it so bad that #{@user.username} no longer deserves these privileges?" %>
  <% end %>
<% else %>
  <%= form_for @user do |f|%>
    <%= f.hidden_field :role, value: 'admin' %>
    <%= f.submit "Grant Admin Privileges", class: 'btn btn-warning btn-sm', confirm: "Are you certain giving #{@user.username} Admin privileges is wise?" %>
  <% end %>
<% end %>