config/routes.rb
GlobalFriends::Application.routes.draw do
  devise_for :users

  resources :properties do
    resources :reviews
  end
  resources :users, only: [:index, :show, :update]

  resources :reviews

  resources :pictures, only: [:show, :destroy, :update]


  root to: 'properties#index'
end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :user
  has_many :pictures
  has_many :reviews

  validates_uniqueness_of :name, scope: :location
  validates :name, presence: true
  validates :location, presence: true
  validates :description, presence: true
  validates :price_day, presence: true
  validates :rental_type, presence: true

  monetize :price_day, as: "price_per_day"
  monetize :price_week, as: "price_per_week", allow_nil: true
  monetize :price_month, as: "price_per_month", allow_nil: true

  def self.expensive
    properties = Property.where("price_day >= 50")
  end

  def self.reasonable
    properties = Property.where("price_day < 50 AND price_day > 20")
  end

  def self.cheap
    properties = Property.where("price_day <= 20")
  end

  def thumbnail(picture)
    self.pictures.delete(picture)
    thumb = self.pictures.new(:user_id => self.user_id, :property_id => self.id)
    thumb.image = picture.image
    thumb.save
  end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

  def index
    @properties = Property.all

    if params[:property].present?
      if params[:property][:rental_type] != "All"
        @properties = @properties.where(rental_type: params[:property][:rental_type])
      end
      # this uses the location name not because it is location, but because there is no single field that holds a string for price.
      if params[:property][:location] == "Expensive"
        @properties = @properties.where("price_day >= 50")
      end
      if params[:property][:location] == "Reasonable"
        @properties = @properties.where("price_day < 50 AND price_day > 20")
      end
      if params[:property][:location] == "Cheap"
        @properties = @properties.where("price_day <= 50")
      end
    end
  end

  def new
    @property = Property.new
  end

  def create
    @property = Property.new property_params
    if !params[:property][:image].nil?
      picture = @property.pictures.new(:user_id => params[:property][:user_id], :property_id => @property.id)
      picture.image = params[:property][:image]
      picture.save
    end
    if @property.save
      flash[:notice] = "Your property was uploaded!  Please hold tight while we verify all the information! (Should take less than 36 months)"
      redirect_to property_path(@property)
    else
      render 'new'
    end
  end

  def show
    @property = Property.find(params[:id])
  end

  def edit
    @property = Property.find(params[:id])
    authorize! :update, @property
  end

  def update
    @property = Property.find(params[:id])
    picture = @property.pictures.new(:user_id => params[:property][:user_id], :property_id => @property.id)
    picture.image = params[:property][:image]
    picture.save
    if @property.update(property_params)
      flash[:notice] = "Your property was updated! Thank you for keeping its information current!"
      redirect_to property_path(@property)
    else
      render 'edit'
    end
  end

  def destroy
    @property = Property.find(params[:id])
    authorize! :destroy, @property
    @property.destroy
    redirect_to root_url, notice: "Property Listing Removed."
  end

private


  def property_params
    params.require(:property).permit(:name, :location, :description, :user_id, :price_day, :price_week, :price_month, :rental_type)
  end
end

app/views/properties/_form.html.erb
<%= form_for @property do |f|%>
  <%= render 'layouts/errors', object: @property %>
  <fieldset>
    <div class='col-lg-3'>
      <legend>Property</legend>
      <div class='form-group'>
        <%= f.label :name %><br />
        <%= f.text_field :name, autofocus: true, class: 'form-control' %>
      </div>
      <div class='form-group'>
        <%= f.label :description %><br />
        <%= f.text_area :description, class: 'form-control' %>
      </div>
      <div class='form-group'>
        <%= f.label :location %><br />
        <%= f.text_field :location, class: 'form-control' %>
      </div>
      <div class='form-group'>
        <%= f.hidden_field :user_id, value: current_user.id %>
      </div>
      <div class='form-group'>
        <%= f.label :rental_type %><br />
        <%= f.select :rental_type, options_for_select(["Entire Place", "Private Room", "Shared Room"]), class: 'form-control' %>
      </div>
      <div class='form-group'>
        <%= f.label :price_day, "Price per Day" %><br />
        <%= f.text_field :price_day, class: 'form-control' %>
      </div>
      <div class='form-group'>
        <%= f.label :price_week, "Price per Week" %><br />
        <%= f.text_field :price_week, class: 'form-control', placeholder: "Optional" %>
      </div>
      <div class='form-group'>
        <%= f.label :price_month, "Price per Month" %><br />
        <%= f.text_field :price_month, data: {role: 'money', a_sep: ',', a_dec: '.'}, class: 'form-control', placeholder: "Optional" %>
      </div>
      <div class='form-group'>
        <%= f.label :image, "Add a Picture of your Property" %><br />
        <%= f.file_field :image %>
      </div>
      <div class='form-group'>
        <%= f.submit "Save Property", class: 'btn btn-success btn-sm' %>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/properties/edit.html.erb
<%= render 'form' %>

app/views/properties/index.html.erb
<h3>Hello, <% if current_user %>
  <%= current_user.username %>
<% else %>
  Global Friend
<% end %>
! Here are all of the properties you could rent.</h3>
<div class="row" id="prop-scan">
  <div class='col-sm-8'>
    <% @properties.each do |property| %>
      <p>
      <%= link_to property.name, property_path(property) %><br/>
      <% if !property.pictures.last.nil? %>
        <%= link_to image_tag(property.pictures.last.image(:thumb)), property_path(property)   %><br />
      <% end %>
      <%= property.description %></p>
      <p>
        <% if can? :update, property %>
          <%= link_to "Edit This Listing", edit_property_path(property), class: 'btn btn-warning btn-xs' %>
        <% end %>
        <% if can? :destroy, property %>
          <%= link_to "Destroy this Listing", property_path(property), :data => { :method => 'delete', :confirm => 'Are you sure you want to reduce this listing to scattered ions?' }, class: 'btn btn-danger btn-xs' %>
        <% end %>
      </p>
    <% end %>

    <p><%= link_to "Add a Property to Rent", new_property_path, class: 'btn btn-success btn-sm' %></p>

    <% if can? :manage, User %>
      <p><%= link_to "Manage Users", users_path, class: 'btn btn-primary btn-sm' %>
    <% end %>

  </div>
  <div class="col-sm-4">
    <span class="descriptiontext"><p>Filter Properties by:</p></span>
    <p>
      <%= form_for Property.new, method: 'get' do |f|%>
        <p><%= f.label :location, "Price Range: " %>
        <%= f.select :location, options_for_select([["All"], ["Expensive"], ["Reasonable"], ["Cheap"]]) %></p>
        <p><%= f.label :rental_type, "Rental Type: " %>
        <%= f.select :rental_type, options_for_select([["All"], ["Entire Place"], ["Private Room"], ["Shared Room"]]) %></p>
        <p><%= f.submit "Filter", class: 'btn btn-success btn-sm' %></p>
      <% end %>
    </p>
  </div>

</div>

app/views/properties/new.html.erb
<%= render 'form' %>

app/views/properties/show.html.erb
<h3><%= @property.name %></h3>
<p><span class="descriptiontext">Description: <br /></span><%= @property.description %></p>
<p><span class="descriptiontext">Location: <br /></span><%= @property.location %></p>
<p><span class="descriptiontext">Type of Rental: <br /></span><%= @property.rental_type %></p>


<% if @property.pictures.length > 0 %>
  <p><span class="descriptiontext">Pictures of this Property:<br /></span><% @property.pictures.shuffle.each do |picture| %>
    <% if can? :update, picture %>
      <%= link_to image_tag(picture.image(:medium)), picture_path(picture) %>
    <% else %>
      <%= image_tag picture.image(:medium) %>
    <% end %>
  <% end %></p>
<% end %>
<p><span class="descriptiontext">Price per Day:</span> <%= humanized_money_with_symbol @property.price_per_day %></p>
<% if @property.price_week %>
  <p><span class="descriptiontext">Price per Week:</span> <%= humanized_money_with_symbol @property.price_per_week %></p>
<% end %>
<% if @property.price_month %>
  <p><span class="descriptiontext">Price per Month:</span>  <%= humanized_money_with_symbol @property.price_per_month %></p>
<% end %>
<p><%= link_to "Return to GlobalFriends Home", root_url, class: 'btn btn-success btn-sm' %>
<% if can? :update, @property %>
  <%= link_to "Edit Your Listing", edit_property_path(@property), class: 'btn btn-warning btn-sm' %>
<% end %>
<% if can? :destroy, @property %>
  <%= link_to "Destroy this Listing", property_path(@property), :data => { :method => 'delete', :confirm => 'Are you sure you want to reduce this listing to scattered ions?' }, class: 'btn btn-danger btn-sm' %>
<% end %>

<% if @property.reviews.length != 0 %>
  <p><h3>Reviews of <%= @property.name %></h3>
    <% @property.reviews.each do |review| %>
      <p><b><%= review.header %></b><br />
      <%= review.body %><br />
      Reviewed by: <%= review.user.username %><br />
      Reviewed on: <%= review.created_at.strftime("%m/%d/%Y") %><br />
      <% if can? :destroy, @property %>
        <%= link_to "Remove this Review", review_path(review), :data => { :method => 'delete', :confirm => 'Are you sure you want to deprive GlobalFriends™ of this review?' }, class: 'btn btn-danger btn-sm' %>
      <% end %>
    <% end %>
  </p>
  <p>

  </p>
<% end %>

<% if current_user %>
  <%= form_for @property.reviews.create do |f|%>
  <fieldset>
    <div class='col-lg-5'>
      <legend>Review this Property</legend>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.hidden_field :property_id, value: @property.id %>
      <div class='form-group'>
        <%= f.label :header, "One Line Summary" %><br />
        <%= f.text_field :header, autofocus: true, class: 'form-control' %>
      </div>
      <div class='form-group'>
        <%= f.label :body, "Your Full Review:" %><br />
        <%= f.text_area :body, class: 'form-control' %>
      </div>
      <div class='form-group'>
        <%= f.submit "Save Review", class: 'btn btn-success btn-sm' %>
      </div>
    </div>
  </fieldset>
<% end %>

<% end %>