config/routes.rb
GlobalFriends::Application.routes.draw do
  devise_for :users

  resources :properties do
    resources :reviews
  end
  resources :users, only: [:index, :show, :update]

  resources :reviews

  resources :pictures, only: [:show, :destroy, :update]


  root to: 'properties#index'
end

app/controllers/reviews_controller.rb
class ReviewsController<ApplicationController
  def create
    @review = Review.new review_params
    if @review.save
      redirect_to property_path(@review.property)
    else
      render 'property#show'
    end
  end

  def destroy
    @review = Review.find(params[:id])
    authorize! :destroy, @review
    @review.destroy
    redirect_to property_path(@review.property), notice: "That nasty review has been obliterated, thank goodness."
  end

  private

  def review_params
    params.require(:review).permit(:user_id, :property_id, :header, :body)
  end
end

app/views/reviews/_form.html.erb
<%= form_for property_reviews_path(@property) do |f|%>
  <%= render 'layouts/errors', object: object %>
  <fieldset>
    <div class='col-lg-5'>
      <legend>Review this Property</legend>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.hidden_field :property_id, value: @property.id %>
      <div class='form-group'>
        <%= f.label :header, "One Line Summary" %><br />
        <%= f.text_field :header, autofocus: true, class: 'form-control' %>
      </div>
      <div class='form-group'>
        <%= f.label :body, "Your Full Review:" %><br />
        <%= f.text_area :body, class: 'form-control' %>
      </div>
      <div class='form-group'>
        <%= f.submit "Save Review", class: 'btn btn-success btn-sm' %>
      </div>
    </div>
  </fieldset>
<% end %>